spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    virtual-host: "/"
  application:
    name: user-manager
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/user_manager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8001
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:6969}
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false

oauth2:
  issuer-uri: http://localhost:8001

server:
  port: 8001

queue:
  notification:
    queue: notification-queue
    exchange: notification-exchange
    routing-key: notification-routing-key

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true